/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package script;

import script.formatdata.FormatData;

public class App {
    public static void main(String[] args) {
        new FormatData().generateData();
    }
}
